apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx2
  name: nginx2
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx2
      name: nginx2
    spec:
      containers:
        - name: nginx
          image: "nginx:1.11"
          resources:
            requests:
              cpu: "500m"
              memory: "64M"
